FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Parknet - Reserva

Essa API define o protocolo da resreva de dados em estacionamentos privados.

## Reserva [/reserva]

### Criar Reserva [POST]

+ Request (application/json)

        {
            "id": 14165431534,
            "id_usuário": 123456721456,
            "id_estacionamento": 4564230874046,
            "carro_id": 42134,
            "entrada_estimada": "1997-07-16T19:20:30+01:00",
            "saida_estimada": "1997-07-16T19:22:30+01:00",
            "pagamento": "dinheiro"
        }

+ Response 200 (application/json)

        {
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/reserva"
        }

### Informações Reserva [GET]

+ Request (application/json)

        {
            "id" = 12345678
        }

+ Response 200 (application/json)

        {
            "id_estacionamento": 123456721456,
            "estacionamento": "Garagem Não Cuidamos",
            "reputacao": 4.5,
            "carro_cor": "Vermelho",
            "carro_Modelo": "vectra",
            "carro_placa": "IBF-2526",
            "entrada_estimada": "1997-07-16T19:20:30+01:00",
            "saida_estimada": "1997-07-16T19:22:30+01:00",
            "entrada": "1997-07-16T19:20:30+01:00",
            "saida": "1997-07-16T19:22:30+01:00",
            "status": "PAGO",
            "pagamento": "dinheiro"
            "valor" : 12.22
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/reserva"
        }

### Informações Reserva [DELETE]

+ Request (application/json)

        {
            "id": 1234654
        }

+ Response 200 (application/json)

        {
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/reservaro "
        }

## Listar Reservas [/reservas]

### Listar Reservas [GET]

+ Request (application/json)

        {
            "id": 1234654
        }

+ Response 200 (application/json)

        {
            "Reservas": [
                {
                    "id": 14165431534,
                    "entrada": "1997-07-16T19:20:30+01:00",
                    "saida": "1997-07-16T19:22:30+01:00",
                    "status": "pendente",
                    "pagamento": "dinheiro"
                },{
                    "id": 14165431525,
                    "entrada": "1997-07-16T19:20:30+01:00",
                    "saida": "1997-07-16T19:22:30+01:00",
                    "status": "pendente",
                    "pagamento": "dinheiro"
                },{
                    "id": 14165431535,
                    "entrada": "1997-07-16T19:20:30+01:00",
                    "saida": "1997-07-16T19:22:30+01:00",
                    "status": "pendente",
                    "pagamento": "dinheiro"
                },{
                    "id": 14165431544,
                    "entrada": "1997-07-16T19:20:30+01:00",
                    "saida": "1997-07-16T19:22:30+01:00",
                    "status": "pendente",
                    "pagamento": "dinheiro"
                }
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/reservas"
        }

## Recomendação [/recomendacoes]

### Listar Recomendações [GET]


+ Request (application/json)

        {
            "id": 463736436946,
            "offset": 0
        }

+ Response 200 (application/json)
        
        {
            "media": 3.5,
            "total": 100,
            "offset": 0,
            "recomendacoes":[
                {
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                },{
                    "recomendacao": "negativo",
                    "mensagem": "Tem Goteira"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                },{
                    "recomendacao": "negativo",
                    "mensagem": "Riscaram o meu carro"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal, Recomendo a todos do ml."
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Atendente gatinha!!!"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                },{
                    "recomendacao": "positivo",
                    "mensagem": "Legal"
                }
            ]
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/recomendacoes"
        }

### Recomendar [POST]

+ Request (application/json)

        {
            "id": 463736436946,
            "recomendação": true,
            "mensagem": "Adorei o piso de lama natural!!!, Recomendo a Todos!!"
        }

+ Response 200 (application/json)

        {
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/recomendacoes"
        }

## Estacionamentos [/estacionamentos]

### Listar Todos os Estacionamentos [GET]

+ Request (application/json)

        {
            "lat": 34,
            "lon": 35,
            "servicos": [
                "lavagem"
                "cobertura",
            ]
        }


+ Response 200 (application/json)

        [
            {
                "estacionamentos": [
                    {
                        "nome": "Garagem Geronimo",
                        "coordenadas": {
                            "lat": 34.534753453,
                            "lon": 34.534753453, 
                        },
                        "servicos": [
                            "lavagem",
                            "teto"
                        ],
                    }, {
                        "nome": "Garagem Jacinto",
                        "coordenadas": {
                            "lat": 34.534753453,
                            "lon": 34.534753453, 
                        },
                        "servicos": [
                            "lavagem",
                            "teto"
                        ],
                    }, {
                        "nome": "Garagem Pinto",
                        "coordenadas": {
                            "lat": 34.534753453,
                            "lon": 34.534753453, 
                        },
                        "servicos": [
                            "lavagem",
                            "teto"
                        ],
                    }, {
                        "nome": "Garagem Norrego",
                        "coordenadas": {
                            "lat": 34.534753453,
                            "lon": 34.534753453, 
                        },
                        "servicos": [
                            "lavagem",
                            "teto"
                        ],
                    }
                ]
            }
        ]

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/estacionamentos"
        }

## Estacionamento [/estacionamento]

### Estacionamento [GET]

+ Request (application/json)

        {
            "id": 74363736
        }
        
+ Response 200 (application/json)

        {
            "nome": "Garagem Norrego",
            "endereço": "Rua dos Bobos Número Zero"
            "abertura": "10:00"
            "fechamento" : "18:00"
            "preço": {
                "primeira hora": 12,
                "hora adicional": 3,
                "per noite": 24
            },
            "coordenadas": {
                "lat": 34.534753453,
                "lon": 34.534753453, 
            },
            "servicos": [
                "lavagem",
                "teto"
            ]
        }

+ Response 400 (application/json)

        {
            "title": "Bad request",
            "detail": "Argumentos da requisição inválidos ou insuficientes",
            "url": "/estacionamento"
        }